In [5]:
convert_file = np.load('data/top_5_compressed/test/Chair/16897b4f5720758492d9da2668ec34c/0_16897b4f5720758492d9da2668ec34c_0_map_grasps.npy')
print(convert_file)

[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  ...
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  ...
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  ...
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 ...

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  ...
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  ...
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  ...
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]]


In [7]:
convert_file.shape

(224, 224, 6)

In [8]:
convert_file.size

301056

In [6]:
import os
import numpy as np
import random
import pathlib

class Shuffler:
    def __init__(self, array: np.ndarray) -> None:
        self.original = array
        self.shuffled = self.original.copy()
        self.x = self.original.shape[1]
        self.y = self.original.shape[0]
        self._pieces = []

    def _split(self, x: int, y: int, x_list: list, y_list: list) -> None:
        if len(self._pieces) > 0:
            self._pieces.clear()

        for x_n, x_piece in enumerate(x_list):
            for y_n, y_piece in enumerate(y_list):
                self._pieces.append(
                    self.original[y_n * y:y_piece, x_n * x:x_piece]
                )

    def _generate_image(self, cols: int) -> None:
        chunks = [
            np.vstack(chunk) for chunk in zip(*[iter(self._pieces)] * cols)
        ]
        self.shuffled = np.hstack(np.array(chunks, dtype=np.uint8))

    def shuffle(self, matrix: tuple) -> np.ndarray:
        x = int(self.x / matrix[0])
        x_list = list(range(x, self.x + 1, x))

        y = int(self.y / matrix[1])
        y_list = list(range(y, self.y + 1, y))

        self._split(x, y, x_list, y_list)
        random.shuffle(self._pieces)

        self._generate_image(matrix[1])
        return self.shuffled

def shuffle_npy_files(src_folder: str, dst_folder: str, matrix: tuple) -> None:
    total_files = sum([len(files) for r, d, files in os.walk(src_folder) if any(f.endswith('.npy') for f in files)])
    processed_files = 0

    for root, _, files in os.walk(src_folder):
        for file in files:
            if file.endswith('.npy'):
                src_file_path = os.path.join(root, file)
                dst_file_path = os.path.join(
                    dst_folder, 
                    os.path.relpath(root, src_folder), 
                    file.replace('.npy', '_shuffle.npy')
                )
                os.makedirs(os.path.dirname(dst_file_path), exist_ok=True)
                
                array = np.load(src_file_path)
                shuffler = Shuffler(array)
                shuffled_array = shuffler.shuffle(matrix)
                np.save(dst_file_path, shuffled_array)

                processed_files += 1
                print(f'Processed {processed_files}/{total_files} files')

src_folder = 'data/top_5_compressed'
dst_folder = 'data_shuffle/top_5_compressed'
matrix = (4, 4)

shuffle_npy_files(src_folder, dst_folder, matrix)


Processed 1/10098 files
Processed 2/10098 files
Processed 3/10098 files
Processed 4/10098 files
Processed 5/10098 files
Processed 6/10098 files
Processed 7/10098 files
Processed 8/10098 files
Processed 9/10098 files
Processed 10/10098 files
Processed 11/10098 files
Processed 12/10098 files
Processed 13/10098 files
Processed 14/10098 files
Processed 15/10098 files
Processed 16/10098 files
Processed 17/10098 files
Processed 18/10098 files
Processed 19/10098 files
Processed 20/10098 files
Processed 21/10098 files
Processed 22/10098 files
Processed 23/10098 files
Processed 24/10098 files
Processed 25/10098 files
Processed 26/10098 files
Processed 27/10098 files
Processed 28/10098 files
Processed 29/10098 files
Processed 30/10098 files
Processed 31/10098 files
Processed 32/10098 files
Processed 33/10098 files
Processed 34/10098 files
Processed 35/10098 files
Processed 36/10098 files
Processed 37/10098 files
Processed 38/10098 files
Processed 39/10098 files
Processed 40/10098 files
Processed

In [2]:
import numpy as np
import cv2 as cv

def npy_to_png(npy_file: str, png_file: str) -> None:
    # Load the .npy file
    array = np.load(npy_file)
    
    # Select the first three channels
    if array.shape[2] >= 3:
        array = array[:, :, :3]
    else:
        raise ValueError("The array does not have enough channels to select 3.")

    # Normalize the array to the range 0-255
    normalized_array = cv.normalize(array, None, 0, 255, cv.NORM_MINMAX)
    
    # Convert to uint8
    uint8_array = normalized_array.astype(np.uint8)
    
    # Ensure the directory exists
    #os.makedirs(os.path.dirname(png_file), exist_ok=True)
    
    # Remove the file if it exists
    if os.path.exists(png_file):
        os.remove(png_file)
    
    # Save as .png file
    cv.imwrite(png_file, uint8_array)
    print(f'Saved {png_file}')





In [16]:
npy_file = 'data/top_5_compressed/test/Chair/16897b4f5720758492d9da2668ec34c/0_16897b4f5720758492d9da2668ec34c_0_map_grasps.npy'
png_file = '0_16897b4f5720758492d9da2668ec34c_0_map_grasps.png'
npy_to_png(npy_file, png_file)

Saved 0_16897b4f5720758492d9da2668ec34c_0_map_grasps.png


In [1]:
npy_file = 'data_shuffle/top_5_compressed/test/Chair/16897b4f5720758492d9da2668ec34c/0_16897b4f5720758492d9da2668ec34c_0_map_grasps_shuffle.npy'
# png_file = '0_16897b4f5720758492d9da2668ec34c_0_map_grasps_shuffle.png'
# npy_to_png(npy_file, png_file)

In [4]:
np.load(npy_file).size

301056